title: Gokhul Abbayi
url: ""
baseurl: ""


tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana, Redsign by koala"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/abbayi"
 - name: "Contact"
   link: "contact"
